[package]
name = "reconcile"
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"
members = [
    "diff",
    "htree",
    "reconcilable",
    "reconcile-service",
    "local-reconcile",
    "examples",
]
