[package]
name = "reconciliate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.7.4"
bincode = "1.3.3"
chrono = "0.4.31"
clap = { version = "4.4.6", features = ["derive"] }
futures = "0.3.28"
rand = "0.8.5"
range-cmp = { git = "https://github.com/Akvize/range-cmp", version = "0.1.0" }
serde = { version = "1.0.188", features = ["derive"] }
tokio = { version = "1.33.0", features = ["macros", "rt-multi-thread", "net", "time"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"

[dev-dependencies]
