[package]
name = "reconcile"
version = "0.0.0-git"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A reconciliation service to sync a key-value map over multiple instances"
repository = "https://github.com/Akvize/reconcile-rs"
exclude = [
    "pre-commit",
    "CONTRIBUTING.md",
]

[[bench]]
name = "bench"
harness = false

[dependencies]
arrayvec = "0.7.4"
bincode = "1.3.3"
chrono = { version = "0.4.31", features = ["serde"] }
ipnet = "2.9.0"
parking_lot = "0.12.1"
rand = "0.8.5"
range-cmp = "0.1.1"
serde = { version = "1.0.192", features = ["derive"] }
tokio = { version = "1.33.0", features = ["net", "time", "rt", "macros"] }
tracing = "0.1.40"

[dev-dependencies]
clap = { version = "4.4.6", features = ["derive"] }
criterion = "0.5.1"
rand = "0.8.5"
tokio = { version = "1.33.0", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = "0.3.17"
