name: tags

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUSTDOCFLAGS: -Dwarnings

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> "$GITHUB_ENV"

      - name: Update Cargo.toml and Cargo.lock versions
        run: |
          sed -i "s/^version = \".*\"/version = \"${VERSION}\"/" Cargo.toml
          sed -i "s/^version = \".*\"/version = \"${VERSION}\"/" Cargo.lock

      - name: Login to crates.io
        run: echo "${{ secrets.CARGO_REGISTRY_TOKEN }}" | cargo login

      - name: Publish crate
        run: cargo publish --allow-dirty